curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/paris
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/london
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/berlin
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/madrid
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/tokyo
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/lima
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/lisboa
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/ibiza
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/piruleta
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/oslo
curl spring-boot-datagrid-challenge-user2-challenge3.apps.cluster-kc2df.kc2df.sandbox790.opentlc.com/weather/stockholm